version: "3.7"

services:
  mysql:
    container_name: 'db'
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: doctors

  service:
    container_name: 'api'
    build:
      context: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
